### PR TITLE
verifying if the authentication token has expired

### PR DESCRIPTION
**Pull request by jlouros**
Small fix to verify if the authentication token has expired.

Also, to avoid any possible confusion "IsAuthorized" and "HasAdminRole" information was removed from local storage. This sets of information should always be fetched from SecurityService.ts (not from local storage)

### CODE REVIEW

**Comment by damienbod** [comment]
@jlouros excellent, thanks

**Comment by damienbod** [comment]
@jlouros testing the branch, I have problems with the menus, merged your change in the devSecurityChanges branch and will try to fixing tonight

**Comment by damienbod** [comment]
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/devSecurityChanges

**Comment by jlouros** [comment]
Sorry about that. I was able to find the referenced .Net Core SDK version, so I haven't tested that out completely. The token expiration portion was something I did on a project that I'm working on.

**Comment by damienbod** [comment]
@jlouros looks good, but the securtiy service throws exceptions now when the has roles or the is authorized methods are used. I'll have a look at end of the week, should be able to merge this then.

**Comment by damienbod** [comment]
thanks for the commit

**Comment by damienbod** [comment]
@jlouros thanks for your change, merged it into the master now. Have you a twitter handle, so I can say thank you?

Thanks for you commit

Greetings Damien

**Comment by jlouros** [comment]
Yup, my twitter handle is @joaogala85.

Thank you for sharing your code and sorry for the untested commit from my part.

Cheers!

**Pull request merged**
