### PR TITLE
Remove bower. Add BuildBundlerMinifier. Add package.json. Modify bundleconfig.json

### PR DESCRIPTION
**Pull request by klanglie**
In this branch I have removed all traces of bower and the dependencies it created. In its place I added BuildBUndlerMinifier. This makes use of package.json and bundleconfig.json to bundle and minify assets installed from package.json. Output is placed into wwwroot/css and wwwroot/js. The minified output is then referenced from _Layout.cshtml and _ValidationScriptsPartial.cshtml.

### CODE REVIEW

**Comment by klanglie** [comment]
I only modified the StsServerIdentity project.

**Comment by damienbod** [comment]
@klanglie It's excellent thanks, tested running it this morning.

**Comment by klanglie** [comment]
I will have to check out your 2FA. Let me know if I can help out with anything. I’ll also keep my eye out for more improvements.

**Comment by damienbod** [comment]
1 small thing. The fonts are missing and need to be added to the dist folder. This could be the same for you.

Greetings Damien

**Comment by klanglie** [comment]
I didn’t notice the missing font. Was it using font awesome? Likely an easy
fix. My project is the same i many ways. But one thing I did was upgrade to
bootstrap4 using a template off of github. VS T4 still uses bootstrap3. I
can look into the font problem. Likely comparing the _layout page with the
previous version will shed some light. Else feel free to mod yourself.

**Pull request merged**
